version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      commitlint:
        patterns:
          - "@commitlint/*"
      vitest:
        patterns:
          - "@vitest/*"
          - "vitest"
      oxc:
        patterns:
          - "oxfmt"
          - "oxlint"
      btravstack:
        patterns:
          - "@btravstack/*"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
