import { defineConfig } from "vitepress";

const SITE_DESCRIPTION =
  "A domain-entity builder on zod v4: branded fields, immutable data, sealed construction, and Result instead of throws.";

const BASE = "/entity/";
const SITE_URL = `https://btravstack.github.io${BASE}`;

// The guide is structured by the four Diátaxis modes (https://diataxis.fr/): a
// learning-oriented Tutorial, task-oriented How-to guides, information-oriented
// Reference, and understanding-oriented Explanation. One shared sidebar carries
// all four so any page can reach any other.
const GUIDE_SIDEBAR = [
  {
    text: "Tutorial",
    items: [{ text: "Getting started", link: "/tutorial/getting-started" }],
  },
  {
    text: "How-to guides",
    items: [
      { text: "Expose an HTTP contract", link: "/how-to/http-contract" },
      { text: "Persist and rehydrate", link: "/how-to/persist-and-rehydrate" },
      { text: "Evolve an entity", link: "/how-to/evolve-an-entity" },
      { text: "Model an aggregate", link: "/how-to/model-an-aggregate" },
      { text: "Number without gaps", link: "/how-to/number-without-gaps" },
      { text: "Test domain logic", link: "/how-to/test-domain-logic" },
    ],
  },
  {
    text: "Reference",
    items: [
      { text: "Declaring an entity", link: "/reference/declaration" },
      { text: "Schema members", link: "/reference/schemas" },
      { text: "Entry points", link: "/reference/entry-points" },
      { text: "Errors", link: "/reference/errors" },
      { text: "Helper types", link: "/reference/types" },
      { text: "API reference", link: "/api/" },
    ],
  },
  {
    text: "Explanation",
    items: [
      { text: "Why entity?", link: "/explanation/why-entity" },
      { text: "Branded fields", link: "/explanation/branded-fields" },
      { text: "No I/O, by design", link: "/explanation/no-io" },
      { text: "Sealed construction", link: "/explanation/sealed-construction" },
      { text: "Immutability", link: "/explanation/immutability" },
      { text: "Why computed re-derives", link: "/explanation/computed-fields" },
      { text: "Tags and identity", link: "/explanation/tags-and-identity" },
      { text: "Unions and roots", link: "/explanation/unions-and-roots" },
      { text: "Errors are values", link: "/explanation/errors-are-values" },
      { text: "Peer dependencies", link: "/explanation/peer-dependencies" },
    ],
  },
];

// The runnable packages under `examples/`. Unlike every fenced block in the
// guide, that code compiles and its specs run in CI.
const EXAMPLES_SECTION = {
  text: "Examples",
  items: [
    { text: "Overview", link: "/examples/" },
    { text: "Billing domain", link: "/examples/billing-domain" },
    { text: "HTTP contract", link: "/examples/billing-api" },
    { text: "Persistence", link: "/examples/billing-persistence" },
  ],
};

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "entity",
  description: SITE_DESCRIPTION,
  base: BASE,
  lang: "en-US",
  cleanUrls: true,

  // `docs/superpowers/` is local design scratch — git-ignored, and not part of
  // the published site. Without this VitePress renders whatever happens to be
  // sitting there into a page and a sitemap entry.
  srcExclude: ["superpowers/**"],

  // The API reference under /api/entity/ is generated by TypeDoc and copied in at
  // build time; its cross-references use relative links TypeDoc resolves itself.
  ignoreDeadLinks: [/^\/api\//, /^\.\/index$/, /^\.\/[a-z-]+$/, /^\.\.\//],

  sitemap: {
    hostname: SITE_URL,
  },

  // Per-page canonical URL + Open Graph / Twitter title & description, so every
  // page shares a correct preview and avoids duplicate-content ambiguity.
  transformPageData(pageData) {
    if (!pageData.relativePath.endsWith(".md")) {
      return;
    }

    const normalizedPath = pageData.relativePath.replace(/^\/+/, "");
    // cleanUrls is true, so the public URL has no `.html` extension: strip
    // `index.md` to the directory and any other `.md` to the bare route.
    const canonicalUrl = `${SITE_URL}${normalizedPath}`
      .replace(/index\.md$/, "")
      .replace(/\.md$/, "");

    pageData.frontmatter ??= {};
    pageData.frontmatter.head ??= [];

    // The /api/ pages (except the hand-written overview) are TypeDoc output copied
    // in at build time — they have no source file in the repo, so "Edit this page"
    // would 404. docs/api/index.md is the one committed file there.
    if (pageData.relativePath.startsWith("api/") && pageData.relativePath !== "api/index.md") {
      pageData.frontmatter.editLink = false;
    }

    pageData.frontmatter.head.push(["link", { rel: "canonical", href: canonicalUrl }]);

    const pageTitle = pageData.title || pageData.frontmatter.title || "entity";
    const pageDescription =
      pageData.description || pageData.frontmatter.description || SITE_DESCRIPTION;

    pageData.frontmatter.head.push(
      ["meta", { property: "og:url", content: canonicalUrl }],
      ["meta", { property: "og:title", content: pageTitle }],
      ["meta", { property: "og:description", content: pageDescription }],
      ["meta", { name: "twitter:title", content: pageTitle }],
      ["meta", { name: "twitter:description", content: pageDescription }],
    );
  },

  themeConfig: {
    logo: { light: "/logo-light.svg", dark: "/logo-dark.svg" },

    nav: [
      // The guide is organised by the four Diátaxis modes; the dropdown links
      // the entry page of each. See the sidebar for the full contents.
      {
        text: "Guide",
        items: [
          { text: "Tutorial", link: "/tutorial/getting-started" },
          { text: "How-to guides", link: "/how-to/http-contract" },
          { text: "Reference", link: "/reference/declaration" },
          { text: "Explanation", link: "/explanation/why-entity" },
        ],
      },
      { text: "Examples", link: "/examples/" },
      { text: "API", link: "/api/" },
      {
        text: "Changelog",
        link: "https://github.com/btravstack/entity/releases",
      },
      // Back to the btravstack hub (links the docs up to the landing page).
      { text: "btravstack", link: "https://btravstack.github.io/" },
    ],

    sidebar: {
      // One shared sidebar across all four Diátaxis sections, so a reader can
      // move between Tutorial / How-to / Reference / Explanation from any page.
      ...Object.fromEntries(
        ["/tutorial/", "/how-to/", "/reference/", "/explanation/"].map((prefix) => [
          prefix,
          GUIDE_SIDEBAR,
        ]),
      ),
      // The examples carry the guide sidebar too, with their own section on
      // top: they are walkthroughs of the same material, so a reader landing on
      // one should still reach every page of the guide.
      "/examples/": [EXAMPLES_SECTION, ...GUIDE_SIDEBAR],
      "/api/": [
        {
          text: "API Reference",
          items: [
            { text: "Overview", link: "/api/" },
            { text: "@btravstack/entity", link: "/api/entity/" },
          ],
        },
      ],
    },

    socialLinks: [
      { icon: "github", link: "https://github.com/btravstack/entity" },
      { icon: "npm", link: "https://www.npmjs.com/package/@btravstack/entity" },
    ],

    footer: {
      message: "Released under the MIT License.",
      copyright: `Copyright © ${new Date().getFullYear()} Benoit TRAVERS`,
    },

    search: {
      provider: "local",
    },

    // The reference pages are dense with `###`-level members; surfacing them in
    // the right-rail outline is what makes them navigable.
    outline: { level: [2, 3] },

    editLink: {
      pattern: "https://github.com/btravstack/entity/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
  },

  vite: {
    // @btravstack/theme's entry imports `vitepress/theme` (which pulls in `.css`)
    // and its own `style.css`. VitePress externalizes node_modules deps in the SSR
    // build, so Node's ESM loader would hit those `.css` files and throw
    // ERR_UNKNOWN_FILE_EXTENSION. Bundling the theme through Vite handles the CSS.
    ssr: { noExternal: ["@btravstack/theme"] },
  },

  head: [
    ["link", { rel: "icon", type: "image/svg+xml", href: `${BASE}logo.svg` }],
    ["meta", { name: "author", content: "Benoit TRAVERS" }],
    ["meta", { name: "robots", content: "index, follow" }],
    ["meta", { name: "application-name", content: "entity" }],
    [
      "meta",
      {
        name: "keywords",
        content:
          "typescript, zod, entity, domain-driven design, ddd, value object, immutable, branded types, json schema, errors as values, result, unthrown",
      },
    ],
    // Open Graph — og:title/description/url are added per page in transformPageData
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:site_name", content: "entity" }],
    ["meta", { property: "og:locale", content: "en_US" }],
    // The 1280x640 social card, on the same template as the other btravstack
    // packages. SVG is not a valid og:image: X, Slack, LinkedIn and Discord all
    // refuse to render one, which is why pointing this at the logo produced no
    // preview at all rather than a small one.
    ["meta", { property: "og:image", content: `${SITE_URL}og-entity.png` }],
    ["meta", { property: "og:image:type", content: "image/png" }],
    // The card's true size. The sibling sites declare 1200x630 (the size the OG
    // docs recommend) while shipping a 1280x640 file; these are measured.
    ["meta", { property: "og:image:width", content: "1280" }],
    ["meta", { property: "og:image:height", content: "640" }],
    [
      "meta",
      {
        property: "og:image:alt",
        content: "entity — a domain-entity builder for TypeScript, on zod v4",
      },
    ],
    // Twitter Card
    // summary_large_image is the wide banner; plain `summary` crops to a square
    // thumbnail beside the title and wastes the card.
    ["meta", { name: "twitter:card", content: "summary_large_image" }],
    ["meta", { name: "twitter:image", content: `${SITE_URL}og-entity.png` }],
    [
      "meta",
      {
        name: "twitter:image:alt",
        content: "entity — a domain-entity builder for TypeScript, on zod v4",
      },
    ],
    // JSON-LD structured data for better SEO
    [
      "script",
      { type: "application/ld+json" },
      JSON.stringify({
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        name: "@btravstack/entity",
        description: SITE_DESCRIPTION,
        applicationCategory: "DeveloperApplication",
        operatingSystem: "Cross-platform",
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
        },
        url: SITE_URL,
        author: {
          "@type": "Person",
          name: "Benoit TRAVERS",
        },
        programmingLanguage: {
          "@type": "ComputerLanguage",
          name: "TypeScript",
          url: "https://www.typescriptlang.org/",
        },
        keywords: "TypeScript, zod, domain-driven design, entity, immutability, Result",
      }),
    ],
  ],
});
